### PR TITLE
Zip Gun and Scrap Armor PR

### PR DESCRIPTION
**Pull request by BigManMassive**
## About The Pull Request
Port of this PR https://github.com/shiptest-ss13/Shiptest/pull/189

## Why It's Good For The Game
More makeshift weapons the better.

## Changelog
:cl:
add: Added makeshift pistol that can be crafted
add: Added makeshift armor that can be crafted
/:cl:

### CODE REVIEW

**Comment by generichuman2** [comment]
yooo based

**Comment by lampstation** [comment]
love this idea you know i all love me some maint rat stuff, trying to get eekker to work on a helmet to make it a full armor set (he might have already done this i dunno) but as the other prs it will be added in with lampstation.

**Comment by lampstation** [comment]
very sorry but theres now an issue with this cause of the nsv guns pr

**Comment by BigManMassive** [comment]
Ok its fixed now

**Comment by generichuman2** [comment]
:troll:

**Pull request merged**
