### PR TITLE
Makes PAYDAY not in the map rotation

### PR DESCRIPTION
**Pull request by generichuman2**
EEEEEEEEEEEE

## About The Pull Request
TITLE

## Why It's Good For The Game
SPEED PR ANY%

## Changelog
:cl:

config: DOES THE THINGS THAT DO THINGS THAT MAKES PAYDAY NOT IN THE MAP ROTATION

/:cl:

### CODE REVIEW

**Comment by lampstation** [comment]
fuck you!!!!!!!!!!!

**Comment by generichuman2** [comment]
FUCK YOU TOOO!!!

**Comment by lampstation** [comment]
FUCK YOU HOE!!!!!!!!!!!!!!!! I AINT MERGING IT NOW YOU GOTTA WAIT LIKE EVERYONE ELSE!!!!!!!!!!!!!!!!

**Comment by generichuman2** [comment]
NNNNNNNNOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!

**Review by BigManMassive — COMMENTED** [review]
Comedy gold

**Comment by lampstation** [comment]
yes 
quite amazing

**Comment by IMadeThisToAskForDiscord** [comment]
@lampstation 
Hey get I get the discord to lampstation? You guys are kind of hard to find anything on outside of this.

**Pull request merged**
